/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum22062026;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author HYPE AMD
 */
public class FormTiket extends javax.swing.JFrame {

    /**
     * Creates new form FormTiket
     */
    public FormTiket() {
        initComponents();
        txtHarga.setEditable(false);
        txtTotal.setEditable(false);
        txtDiskon.setEditable(false);
        txtBayar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTujuan = new javax.swing.ButtonGroup();
        lblJudul = new javax.swing.JLabel();
        lblTujuan = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        rbBkt = new javax.swing.JRadioButton();
        rbSolok = new javax.swing.JRadioButton();
        rbPar = new javax.swing.JRadioButton();
        cbKelas = new javax.swing.JComboBox<>();
        btnHarga = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        lblTiket = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        lblBayar = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUang = new javax.swing.JTextField();
        btnSelesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setText("FORM PEMBELIAN TIKET BUS NUSANTARA");

        lblTujuan.setText("Tujuan");

        lblKelas.setText("Kelas");

        btnGroupTujuan.add(rbBkt);
        rbBkt.setText("Bukittinggi");
        rbBkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBktActionPerformed(evt);
            }
        });

        btnGroupTujuan.add(rbSolok);
        rbSolok.setText("Solok");
        rbSolok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSolokActionPerformed(evt);
            }
        });

        btnGroupTujuan.add(rbPar);
        rbPar.setText("Pariaman");
        rbPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParActionPerformed(evt);
            }
        });

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Kelas", "Ekonomi", "Bisnis", "Eksekutif" }));

        btnHarga.setText("Harga 1 Tiket");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        lblTiket.setText("Masukan Jumlah Tiket");

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        lblTotal.setText("Total Harga");

        lblDiskon.setText("Diskon");

        lblBayar.setText("Total Pembayaran");

        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });

        txtDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiskonActionPerformed(evt);
            }
        });

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setText("Masukkan Uang");

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTujuan)
                                    .addComponent(lblKelas))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbBkt)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbSolok)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbPar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHarga))
                                    .addComponent(lblJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                                .addGap(19, 33, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTotal)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblBayar)
                                                .addGap(51, 51, 51)
                                                .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHarga)
                            .addComponent(txtTotal)
                            .addComponent(txtDiskon))
                        .addContainerGap(19, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelesai)
                .addGap(210, 210, 210))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTujuan)
                    .addComponent(rbBkt)
                    .addComponent(rbSolok)
                    .addComponent(rbPar))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelas)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal)
                    .addComponent(lblTiket)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiskon)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBayar)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btnHitung)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addComponent(btnSelesai)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBktActionPerformed

    private void rbSolokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSolokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSolokActionPerformed

    private void rbParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbParActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbParActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        int kelas = (int)cbKelas.getSelectedIndex();
        if(!rbBkt.isSelected()&&!rbSolok.isSelected()&&!rbPar.isSelected()){
            JOptionPane.showMessageDialog(this,"Tujuan Belum Dipilih","Pesan Kesalahan",ERROR_MESSAGE);
        }else if(cbKelas.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Kelas Belum Dipilih","Pesan Kesalahan",ERROR_MESSAGE);
        }
        switch(kelas){
            case 1: if(rbBkt.isSelected())
                        txtHarga.setText("25000");
                    else if (rbSolok.isSelected())
                        txtHarga.setText("20000");
                    else if (rbPar.isSelected())
                        txtHarga.setText("15000");
                    break;
            case 2: if(rbBkt.isSelected())
                        txtHarga.setText("50000");
                    else if (rbSolok.isSelected())
                        txtHarga.setText("40000");
                    else if (rbPar.isSelected())
                        txtHarga.setText("30000");
                    break;
            case 3: if(rbBkt.isSelected())
                        txtHarga.setText("80000");
                    else if (rbSolok.isSelected())
                        txtHarga.setText("70000");
                    else if (rbPar.isSelected())
                        txtHarga.setText("55000");
                    break;
        }
        
    }//GEN-LAST:event_btnHargaActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarActionPerformed

    private void txtDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiskonActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try{
            int jumlah = Integer.parseInt(txtJumlah.getText());
            if (jumlah < 0){
                JOptionPane.showMessageDialog(this, "Jumlah tiket gak bisa min", "Tiker Error", ERROR_MESSAGE);
                txtJumlah.setText("");
                txtJumlah.requestFocus();
            }
            double harga = Double.parseDouble(txtHarga.getText());
            double total = jumlah * harga;
            double diskon = 0;
            if(jumlah >5 ){
                diskon = 0.1*total;
            }
            double bayar = total - diskon;
            txtTotal.setText(Double.toString(total));
            txtDiskon.setText(Double.toString(diskon));
            txtBayar.setText(Double.toString(bayar));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Jumlah Harus Bilangan Bulat","Pesan Error", ERROR_MESSAGE);
            txtJumlah.setText("");
            txtJumlah.requestFocus();
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtHarga.setText("");
        txtJumlah.setText("");
        txtTotal.setText("");
        txtDiskon.setText("");
        txtBayar.setText("");
        cbKelas.setSelectedIndex(0);
        btnGroupTujuan.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int pil = JOptionPane.showConfirmDialog(this, "Apakah Ingin Keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(pil==JOptionPane.YES_OPTION){
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        try {
            double uang = Double.parseDouble(txtUang.getText());
            int jumlah = Integer.parseInt(txtJumlah.getText());
            
            if (jumlah < 0){
                JOptionPane.showMessageDialog(this, "Jumlah tiket gak bisa min", "Tiket Error", ERROR_MESSAGE);
                txtJumlah.setText("");
                txtJumlah.requestFocus();
                return;
            }

            double harga = Double.parseDouble(txtHarga.getText());
            double total = jumlah * harga;
            double diskon = 0;
            
            if(jumlah > 5 ){
                diskon = 0.1 * total;
            }
            
            double bayar = total - diskon;

            if (uang < bayar) {
                JOptionPane.showMessageDialog(this, "Uang pembayaran kurang!", "Pembayaran Error", ERROR_MESSAGE);
                txtUang.requestFocus();
                return; // Hentikan eksekusi jika uang kurang
            }

            double kembalian = uang - bayar;

            String tujuan = "";
            if (rbBkt.isSelected()) tujuan = "Bukittinggi";
            else if (rbSolok.isSelected()) tujuan = "Solok";
            else if (rbPar.isSelected()) tujuan = "Pariaman";

            String kelas = cbKelas.getSelectedItem().toString();

            String struk = "========== STRUK PESANAN ==========\n\n" +
                           "Tujuan\t\t: " + tujuan + "\n" +
                           "Kelas\t\t: " + kelas + "\n" +
                           "Harga 1 Tiket\t: Rp " + harga + "\n" +
                           "Jumlah Tiket\t: " + jumlah + "\n" +
                           "Total Harga\t: Rp " + total + "\n" +
                           "Diskon\t\t: Rp " + diskon + "\n" +
                           "----------------------------------------------------\n" +
                           "Total Bayar\t: Rp " + bayar + "\n" +
                           "Uang Diterima\t: Rp " + uang + "\n" +
                           "Kembalian\t: Rp " + kembalian + "\n\n" +
                           "Terima Kasih Telah Menggunakan Bus Nusantara!";
                           
            JOptionPane.showMessageDialog(this, struk, "Detail Pesanan Tiket", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Pastikan semua data sudah dihitung dan uang diisi dengan angka yang benar!", "Pesan Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormTiket().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGroupTujuan;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBayar;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblTiket;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTujuan;
    private javax.swing.JRadioButton rbBkt;
    private javax.swing.JRadioButton rbPar;
    private javax.swing.JRadioButton rbSolok;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUang;
    // End of variables declaration//GEN-END:variables
}
